### PR TITLE
Fix some issues in 1.21.1

### LINKED ISSUE #1082: Holding a blueprint causes crash
mod version: 1.6.0-pre158
minecraft version: 1.21.1 with neoforge 21.1.143

```
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 2025-04-06 23:07:57
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.component.CustomData.hashCode()" because the return value of "net.minecraft.world.item.ItemStack.get(java.util.function.Supplier)" is null
	at TRANSFORMER/littletiles@1.6.0-pre158/team.creative.littletiles.client.tool.LittleToolPlacer.tick(LittleToolPlacer.java:176) ~[LittleTiles_BETA_v1.6.0-pre158_mc1.21.1.jar%23180!/:1.6.0-pre158] {re:classloading}
	at TRANSFORMER/littletiles@1.6.0-pre158/team.creative.littletiles.client.render.overlay.PreviewRenderer.tick(PreviewRenderer.java:117) ~[LittleTiles_BETA_v1.6.0-pre158_mc1.21.1.jar%23180!/:1.6.0-pre158] {re:classloading}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%23172!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.2.jar%23172!/:?] {}
	at TRANSFORMER/neoforge@21.1.143/net.neoforged.neoforge.client.ClientHooks.dispatchRenderStage(ClientHooks.java:292) ~[neoforge-21.1.143-universal.jar%23178!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.LevelRenderer.renderLevel(LevelRenderer.java:1228) ~[client-1.21.1-20240808.144430-srg.jar%23177!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:littletiles.mixins.json:client.render.LevelRendererAccessor from mod littletiles,pl:mixin:APP:littletiles.mixins.json:client.render.LevelRendererMixin from mod littletiles,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.renderLevel(GameRenderer.java:1271) ~[client-1.21.1-20240808.144430-srg.jar%23177!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:littletiles.mixins.json:client.render.GameRendererAccessor from mod littletiles,pl:mixin:APP:littletiles.mixins.json:client.render.GameRendererMixin from mod littletiles,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1024) ~[client-1.21.1-20240808.144430-srg.jar%23177!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:littletiles.mixins.json:client.render.GameRendererAccessor from mod littletiles,pl:mixin:APP:littletiles.mixins.json:client.render.GameRendererMixin from mod littletiles,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.runTick(Minecraft.java:1195) ~[client-1.21.1-20240808.144430-srg.jar%23177!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.run(Minecraft.java:807) ~[client-1.21.1-20240808.144430-srg.jar%23177!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21.1-20240808.144430-srg.jar%23177!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.38/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.38.jar%23165!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.38/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.38.jar%23165!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.38/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.38.jar%23165!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.38/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.38.jar%23165!/:4.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23168!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23168!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23168!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23168!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23168!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23168!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23168!/:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at TRANSFORMER/littletiles@1.6.0-pre158/team.creative.littletiles.client.tool.LittleToolPlacer.tick(LittleToolPlacer.java:176) ~[LittleTiles_BETA_v1.6.0-pre158_mc1.21.1.jar%23180!/:1.6.0-pre158] {re:classloading}
	at TRANSFORMER/littletiles@1.6.0-pre158/team.creative.littletiles.client.render.overlay.PreviewRenderer.tick(PreviewRenderer.java:117) ~[LittleTiles_BETA_v1.6.0-pre158_mc1.21.1.jar%23180!/:1.6.0-pre158] {re:classloading}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%23172!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.2.jar%23172!/:?] {}
	at TRANSFORMER/neoforge@21.1.143/net.neoforged.neoforge.client.ClientHooks.dispatchRenderStage(ClientHooks.java:292) ~[neoforge-21.1.143-universal.jar%23178!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.LevelRenderer.renderLevel(LevelRenderer.java:1228) ~[client-1.21.1-20240808.144430-srg.jar%23177!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:littletiles.mixins.json:client.render.LevelRendererAccessor from mod littletiles,pl:mixin:APP:littletiles.mixins.json:client.render.LevelRendererMixin from mod littletiles,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.renderLevel(GameRenderer.java:1271) ~[client-1.21.1-20240808.144430-srg.jar%23177!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:littletiles.mixins.json:client.render.GameRendererAccessor from mod littletiles,pl:mixin:APP:littletiles.mixins.json:client.render.GameRendererMixin from mod littletiles,pl:mixin:A,pl:runtimedistcleaner:A}
-- Uptime --
Details:
	JVM uptime: 37.786s
	Wall uptime: 30.488s
	High-res time: 36.033s
	Client ticks: 485 ticks / 24.250s
Stacktrace:
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.fillReport(Minecraft.java:2394) ~[client-1.21.1-20240808.144430-srg.jar%23177!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.emergencySaveAndCrash(Minecraft.java:868) ~[client-1.21.1-20240808.144430-srg.jar%23177!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.run(Minecraft.java:828) ~[client-1.21.1-20240808.144430-srg.jar%23177!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21.1-20240808.144430-srg.jar%23177!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.38/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.38.jar%23165!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.38/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.38.jar%23165!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.38/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.38.jar%23165!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.38/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.38.jar%23165!/:4.0] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23168!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23168!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23168!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23168!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23168!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23168!/:?] {}
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23168!/:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {}
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {}


-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['pariring'/1, l='ClientLevel', x=-170.70, y=70.78, z=170.98]]
	Chunk stats: 961, 437
	Level dimension: minecraft:overworld
	Level spawn location: World: (-176,68,160), Section: (at 0,4,0 in -11,4,10; chunk contains blocks -176,-64,160 to -161,319,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 170 game time, 170 day time
	Server brand: neoforge
	Server type: Integrated singleplayer server
	Tracked entity count: 67

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, mod_resources, mod/littletiles, mod/creativecore, mod/neoforge

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Mac OS X (aarch64) version 15.0
	Java Version: 21.0.2, Amazon.com Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Amazon.com Inc.
	Memory: 716852024 bytes (683 MiB) / 1518338048 bytes (1448 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 10
	Processor Vendor: Apple Inc.
	Processor Name: Apple M2 Pro
	Identifier: Apple Inc. Family 0xda33d83d Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Avalanche + Blizzard
	Frequency (GHz): 3.50
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 10
	Graphics card #0 name: Apple M2 Pro
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MiB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MiB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MiB): 32768.00
	Virtual memory used (MiB): 23413.67
	Swap memory total (MiB): 0.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): available: 328325.28, total: 948584.19
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 328325.28, total: 948584.19
	Space in storage for io.netty.native.workdir (MiB): available: 328325.28, total: 948584.19
	Space in storage for java.io.tmpdir (MiB): available: 328325.28, total: 948584.19
	Space in storage for workdir (MiB): available: 328325.28, total: 948584.19
	JVM Flags: 0 total; 
	Launched Version: neoforge-21.1.143
	Launcher name: X Minecraft Launcher (0.49.3)
	Backend library: LWJGL version 3.3.3+5
	Backend API: Apple M2 Pro GL version 4.1 Metal - 89.3, Apple
	Window size: 2292x1293
	GFLW Platform: cocoa
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Is Modded: Definitely; Client brand changed to 'neoforge'; Server brand changed to 'neoforge'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	GPU Warnings: version: Metal
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, mod_resources, mod/littletiles, mod/creativecore, mod/neoforge
	Current Language: en_us
	Locale: en_KR
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: 10x Apple M2 Pro
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['pariring'/1, l='ServerLevel[New World]', x=-170.70, y=70.78, z=170.98]]
	Active Data Packs: vanilla, mod_data, mod/littletiles (incompatible), mod/creativecore (incompatible), mod/neoforge
	Available Data Packs: bundle, trade_rebalance, vanilla, mod/creativecore (incompatible), mod/littletiles (incompatible), mod/neoforge, mod_data
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 2270569505838268952
	ModLauncher: 11.0.4+main.d2e20e43
	ModLauncher launch target: forgeclient
	ModLauncher services: 
		sponge-mixin-0.15.2+mixin.0.8.7.jar mixin PLUGINSERVICE 
		loader-4.0.38.jar slf4jfixer PLUGINSERVICE 
		loader-4.0.38.jar runtime_enum_extender PLUGINSERVICE 
		at-modlauncher-10.0.1.jar accesstransformer PLUGINSERVICE 
		loader-4.0.38.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-11.0.4.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-11.0.4.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		javafml@4.0
		lowcodefml@4.0
		minecraft@4.0
	Mod List: 
		CreativeCore_NEOFORGE_v2.13.0_mc1.21.1.jar        |CreativeCore                  |creativecore                  |2.13.0              |Manifest: NOSIGNATURE
		LittleTiles_BETA_v1.6.0-pre158_mc1.21.1.jar       |LittleTiles                   |littletiles                   |1.6.0-pre158        |Manifest: NOSIGNATURE
		client-1.21.1-20240808.144430-srg.jar             |Minecraft                     |minecraft                     |1.21.1              |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		neoforge-21.1.143-universal.jar                   |NeoForge                      |neoforge                      |21.1.143            |Manifest: NOSIGNATURE
	Crash Report UUID: 6023262b-88b2-443b-8ab5-1d8e5894f0b6
	FML: 4.0.38
	NeoForge: 21.1.143
```

### PR DESCRIPTION
**Pull request by paring-chan**
- [x] Fixes #1082
- [x] Fixes client crashing on survival mode when using hammer

### CODE REVIEW

File: src/main/java/team/creative/littletiles/client/tool/LittleToolPlacer.java [hunk 1]
```diff
@@ -173,7 +173,9 @@ public void tick(Level level, Player player, @Nullable BlockHitResult blockHit)
         var mode = placer.getPlacementMode(stack);
         var matrix = placer.getMatrix(stack);
         var hasTiles = placer.hasTiles(stack);
-        var hash = stack.get(LittleTilesRegistry.DATA).hashCode();
+        var data = stack.get(LittleTilesRegistry.DATA);
+        if (data == null) return;
```
Comment (CreativeMD) [inline src/main/java/team/creative/littletiles/client/tool/LittleToolPlacer.java]: Oh totally forgot about it, instead of returning I would rather set the hash to zero. Because the code below can be relevant.

File: src/main/java/team/creative/littletiles/client/tool/LittleToolPlacer.java [hunk 2]
```diff
@@ -410,7 +412,10 @@ public boolean onRightClick(Level level, Player player, BlockHitResult result) {
         if (!built)
             return false;
         if (!checkForWorker())
+        {
+            if (worker == null) return false;
             builtResult = worker.join();
```
Comment (CreativeMD) [inline src/main/java/team/creative/littletiles/client/tool/LittleToolPlacer.java:417]: Oh alright, if there is nothing to place, worker will probably be null and in that case nothing should happen. Could also be replaced with builtEmpty, but I guess it does not matter.

File: src/main/java/team/creative/littletiles/client/tool/shaper/LittleToolShaper.java [hunk 3]
```diff
@@ -226,10 +226,10 @@ private boolean interact(Level level, Player player, ItemStack stack, BlockHitRe
                         builtShapeConfig);
                 shaper.shapeFinished(level, player, stack, builtSelection, boxes);
                 clearPositions();
-                return true;
+                return false;
             } else if (hit != null) {
                 positions.add(last.copy());
-                return true;
```
Comment (CreativeMD) [inline src/main/java/team/creative/littletiles/client/tool/shaper/LittleToolShaper.java:232]: Not sure why you would return false here? Return true makes sure the action is consumed and all other interactions are cancelled.

**Review by CreativeMD — CHANGES_REQUESTED** [review]

**Comment by CreativeMD** [comment]
Thank you so much! It's quite rather to see someone taking action and helping out!

File: src/main/java/team/creative/littletiles/client/tool/shaper/LittleToolShaper.java (hunk 3 above)
Comment (paring-chan) [reply src/main/java/team/creative/littletiles/client/tool/shaper/LittleToolShaper.java:232]: I turned that to false because the tool repeats too fast in survival mode. Is there any better way to delay this?
(sorry I'm not really good at minecraft modding)

video: https://youtu.be/ZiuElN9GibY

Because of this, I also want to change left click handling on blueprint item because the same one happens

**Comment by CreativeMD** [comment]
Alright. Again thank you so much for your effort! I will try to fix the survival issue with a different way, but I guess for now that fix works.
